"""updated user

Revision ID: 0b1b54fb960e
Revises: 310f09d739f8
Create Date: 2026-05-20 21:18:00.124524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1b54fb960e'
down_revision: Union[str, Sequence[str], None] = '310f09d739f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['mobile_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'otp_attempts')
    # ### end Alembic commands ###
