"""updated usermodel

Revision ID: 2509184c9867
Revises: 69d6b7eabaf7
Create Date: 2026-05-13 23:09:16.258757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2509184c9867'
down_revision: Union[str, Sequence[str], None] = '69d6b7eabaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_blacklisted_tokens_expires', 'blacklisted_tokens', ['expires_at'], unique=False)
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.create_index('idx_users_mobile_number', 'users', ['mobile_number'], unique=False)
    op.create_unique_constraint(None, 'users', ['mobile_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_mobile_number', table_name='users')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'mobile_number')
    op.drop_index('idx_blacklisted_tokens_expires', table_name='blacklisted_tokens')
    # ### end Alembic commands ###
