"""updated usermodel

Revision ID: 4815575745a7
Revises: 6783313d34d0
Create Date: 2026-05-12 21:58:18.456302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4815575745a7'
down_revision: Union[str, Sequence[str], None] = '6783313d34d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.Enum('email', 'google', name='authprovider'), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('hashed_otp', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_sub', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('idx_users_phone_number'), table_name='users')
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_google_sub', 'users', ['google_sub'], unique=False)
    op.create_unique_constraint(None, 'users', ['google_sub'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firebase_uid', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_google_sub', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'hashed_otp')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
