"""expense model

Revision ID: 991df4c3c072
Revises: 3efe3f6b5ef2
Create Date: 2026-05-20 21:06:43.267067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991df4c3c072'
down_revision: Union[str, Sequence[str], None] = '3efe3f6b5ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_blacklisted_tokens_expires'), table_name='blacklisted_tokens')
    op.drop_index(op.f('idx_user_budgets_user_id'), table_name='user_budgets')
    op.drop_constraint(op.f('user_budgets_user_id_key'), 'user_budgets', type_='unique')
    op.drop_column('user_budgets', 'id')
    op.drop_index(op.f('idx_users_mobile_number'), table_name='users')
    op.drop_constraint(op.f('users_mobile_number_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_mobile_number_key'), 'users', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    op.add_column('user_budgets', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('user_budgets_user_id_key'), 'user_budgets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_budgets_user_id'), 'user_budgets', ['user_id'], unique=False)
    op.create_index(op.f('idx_blacklisted_tokens_expires'), 'blacklisted_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
