"""created budget model

Revision ID: 9e036bf9c7eb
Revises: e22cf542b4ea
Create Date: 2026-05-22 09:16:03.491092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e036bf9c7eb'
down_revision: Union[str, Sequence[str], None] = 'e22cf542b4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_active',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('weekly_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tasks_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('budget_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('weekly_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tasks_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_history_user_id', 'budget_history', ['user_id'], unique=False)
    op.create_index('uq_budget_history_user_week', 'budget_history', ['user_id', 'week_start'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_budget_history_user_week', table_name='budget_history')
    op.drop_index('ix_budget_history_user_id', table_name='budget_history')
    op.drop_table('budget_history')
    op.drop_table('budget_active')
    # ### end Alembic commands ###
