"""user model

Revision ID: bf97b463eb54
Revises: 9e036bf9c7eb
Create Date: 2026-05-27 20:56:06.423533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf97b463eb54'
down_revision: Union[str, Sequence[str], None] = '9e036bf9c7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weekly_budget', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_budget')
    # ### end Alembic commands ###
